name: lpsolvers
channels:
    - conda-forge
dependencies:
    - pip >= 21.3.1
    - proxsuite
    - pip:
        - cvxopt >= 1.2.6
        - cvxpy >= 1.1.11
        - ortools >= 9.8.3296
        - pycddlib >= 2.1.7
        # sphinx-rtd-theme raises an error with sphinx >= 7
        - sphinx < 7.0.0
        - sphinx-autodoc-typehints
        - sphinx-mathjax-offline
        - sphinx-rtd-theme >= 0.5.1
